### ISSUE TITLE
False Positive - Win

### ISSUE THREAD

**Issue by Jimjule** [Jimjule/deep_red_yellow_connect4#7]
A bot v bot match generated a win where there were not four counters in a row.
I suspect that it is an issue to do with how vertical wins are checked.
![ai_false_win](https://user-images.githubusercontent.com/17428597/56664297-ca37d280-669f-11e9-808e-501f4c6423b6.png)

**Comment by steve-f-kahn** [comment]
Issue relates to how vertical wins where calculated. It has now been changed to work in a similar function to the other directions. The issue is now resolved
