### ISSUE TITLE
2 Consecutive Entries to a Full Column Causes Crash

### ISSUE THREAD

**Issue by Jimjule** [Jimjule/deep_red_yellow_connect4#9]
When a column is full, users are asked to make another, legal move. The code does not account for consecutive illegal moves, and pushes illegal moves to the array, before crashing.
![consecutive_illegal_move_error](https://user-images.githubusercontent.com/17428597/56666587-1b49c580-66a4-11e9-99bd-919e09f288fe.png)

**Comment by steve-f-kahn** [comment]
Brenda has patched the fix.
